### ISSUE TITLE
Failing test in new installation

### ISSUE THREAD

**Issue by erikedlund** [haddocking/DeepRank-GNN-esm#14]
Thank you for publishing such a cool tool! I'm running into some issues installing and using the scoring function. 

First, I'm seeing tests failing in a fresh installation:

FAILED tests/test_biowrappers.py::TestBioWrappers::test_depth_res - Failed: Unexpected success
=================================================== 1 failed, 21 passed, 3 xfailed, 144223 warnings in 347.77s (0:05:47) ================================================

[DeepRank-GNN-esm_test.txt](https://github.com/user-attachments/files/17996738/DeepRank-GNN-esm_test.txt)

When I attempt to use the model, an assertion error is thrown suggesting the embeddings are invalid:

`$ deeprank-gnn-esm-predict ./053_5.pdb C A ../paper_pretrained_models/scoring_of_docking_models/gnn_esm/treg_yfnat_b64_e20_lr0.001_foldall_esm.pth.tar 
 2024-12-03 20:51:26,609 predict:60 INFO - Setting up workspace - /share/data/public/edlunde/git/DeepRank-GNN-esm/test/053_5-gnn_esm_pred_C_A
 2024-12-03 20:51:26,616 predict:69 INFO - Renumbering PDB file.
 2024-12-03 20:51:26,685 predict:112 INFO - Reading sequence of PDB 053_5.pdb
 2024-12-03 20:51:26,716 predict:138 INFO - Generating embedding for protein sequence.
 2024-12-03 20:51:26,716 predict:139 INFO - ################################################################################
 2024-12-03 20:51:33,577 predict:154 INFO - Read /share/data/public/edlunde/git/DeepRank-GNN-esm/test/053_5-gnn_esm_pred_C_A/all.fasta with 2 sequences
 2024-12-03 20:51:33,586 predict:164 INFO - Processing 1 of 1 batches (2 sequences)
 2024-12-03 20:51:43,586 predict:206 INFO - ################################################################################
 2024-12-03 20:51:43,669 predict:211 INFO - Generating graph, using 31 processors
Graphs added to the HDF5 file
Traceback (most recent call last):
  File "~/conda/envs/deeprank-gnn-esm-cpu-env/bin/deeprank-gnn-esm-predict", line 8, in <module>
    sys.exit(main())
  File "~/conda/envs/deeprank-gnn-esm-cpu-env/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 335, in main
    graph = create_graph(pdb_path=pdb_file.parent, workspace_path=workspace_path)
  File "~/conda/envs/deeprank-gnn-esm-cpu-env/lib/python3.9/site-packages/deeprank_gnn/predict.py", line 216, in create_graph
    GraphHDF5(
  File "~/conda/envs/deeprank-gnn-esm-cpu-env/lib/python3.9/site-packages/deeprank_gnn/GraphGenMP.py", line 141, in __init__
    self._add_embedding(outfile=outfile, pdbs=pdbs, embedding_path=embedding_path)
  File "~/conda/envs/deeprank-gnn-esm-cpu-env/lib/python3.9/site-packages/deeprank_gnn/GraphGenMP.py", line 247, in _add_embedding
    assert not torch.all(torch.eq(embedding_tersor, 0))
AssertionError`

I am running in CPU mode, for what it's worth, but the test failure seems unrelated.

**Comment by erikedlund** [comment]
I've discovered a workaround for the crash. My .pdb files are named with a unique convention. Renaming the files to a pattern matching the RCSB convention (e.g. 1XXX.pdb) allows DeepRank-GNN-esm to proceed.

**Comment by ntxxt** [comment]
Thank you for your interest in our tool!
Good work!

**Comment by ntxxt** [comment]
Hi there, 

In what part is the code failing? The assert check ensures embedding is added correctly to the graph.  

If you re-name your pdb file as xxxx.pdb, the code should run fine. Also, try to use pdb_tidy command from pdb-tools to clean the pdb file if it is not the standard format. 
I can also look at your input pdb file if you cannot identify the issue. 

Best,
Xiaotong

**Comment by erikedlund** [comment]
This is the` pytest test` output from the installation instructions. I filed this as a single issue because I wondered if the test failure indicated the source of the problem with the file names but it seems like the assumption for their length is intended.

FAILED **tests/test_biowrappers.py::TestBioWrappers::test_depth_res - Failed: Unexpected success**
=================================================== 1 failed, 21 passed, 3 xfailed, 144223 warnings in 347.77s (0:05:47) ================================================

**Comment by erikedlund** [comment]
Here's the complete output of a test failure from a fresh installation on a new Ubuntu machine with a 4090.
[DeepRank-GNN-esm-test-failures.txt](https://github.com/user-attachments/files/18216311/DeepRank-GNN-esm-test-failures.txt)

Let me know if there are any other logs I can provide.

**Comment by ntxxt** [comment]
Hi there, sorry for the late response, 

I just took a look, and the error is caused by this line, which involves matrix calculation based on the predicted results:

```
self.FDR = false_positive / (true_positive + false_positive)
```
The issue arises because, in this case, the test PDB and targets are 'fake' data, As a result, both the true positive and false positive values predicted by the model are 0, leading to a division by zero error.

If you passed all the other tests, means your environment is set up correctly and ready to be used. This error is unlikely to occur in real-world scenarios, so it shouldn't be a concern moving forward.
